### ISSUE TITLE
Osvetljenje objekata

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG94-shape-fitting#1]
Neophodno je da 2d objekti koji se krecu po traci i koji stoje na slici imaju adekvatno postavljeno osvetljenje (normale).

**Comment by tamarastojkovic** [comment]
@rastko-djordjevic-edu Da li mozete da mi pojasniti na sta konkretno mislite, posto nisam sigurna da dobro razumem? Da li treba glNormal nekako za svaki Vertex odnosno oblik?

**Comment by tamarastojkovic** [comment]
Dodato je osvetljenje 2D objektima koji se krecu po traci i koji se nalaze na slici-postavljene su normale.
