### ISSUE TITLE
Racunanje poena

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG94-shape-fitting#2]
Ako dobro razumem igru trebalo bi da se klikne space dok je neki objekat u kvadratu koji je na centru ekrana, i potom da se misom klikne na isti objekat na slici. Ovo izgleda kao da nekada radi a nekada ne radi.

**Comment by tamarastojkovic** [comment]
@rastko-djordjevic-edu Ja sam radila projekat na VM za Linux i pretpostavljam da se zbog toga ne uklapaju neke koordinate, jer meni radi za sve slucajeve. Imam zbog toga proporciju koja racuna koordinate na proizvoljnom ekranu, pa mi nije jasno sto i dalje ne radi. Kako bih mogla to da resim, s obzirom na to da na mom racunaru radi sve normalno?

**Comment by tamarastojkovic** [comment]
Ispravljen bug  vezan za klik misem.
